project:
  type: book

book:
  title: "Statistical Rethinking in Tidyverse and Stan"
  subtitle: "Notes and exercises from the book, 2nd Edition"
  author: "Hamed Bastan-Hagh"
  search: true
  repo-url: "https://github.com/hamedbh/stat-rethinking"
  repo-actions: [edit]
  sharing: [twitter, facebook]
  page-navigation: true
  chapters:
    - index.qmd
    - 01-golem.qmd
    - 02-small-worlds-large-worlds.qmd
    - 03-sampling-imaginary.qmd
    - 04-geocentric-models.qmd
    - 05-many-variables-spurious-waffles.qmd
    - 06-haunted-dag-causal-terror.qmd
    - 07-ulysses-compass.qmd
    - 08-conditional-manatees.qmd
    - 09-markov-chain-monte-carlo.qmd
    - 10-big-entropy-glm.qmd
    - 11-god-spiked-integers.qmd
    - 12-monsters-mixtures.qmd
    - 13-models-memory.qmd

toc: true
toc-depth: 3

format:
  html:
    theme: simplex
    highlight-style: textmate
